/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as AuthCreateAccountIndexRouteImport } from './routes/(Auth)/create-account/index'
import { Route as AuthLoginIndexRouteImport } from './routes/(Auth)/login/index'

const appIndexRoute = appIndexRouteImport.update({
  id: '/(app)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCreateAccountIndexRoute = AuthCreateAccountIndexRouteImport.update({
  id: '/(Auth)/create-account/',
  path: '/create-account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/(Auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRoute
  '/create-account/': typeof AuthCreateAccountIndexRoute
  '/login/': typeof AuthLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof appIndexRoute
  '/create-account': typeof AuthCreateAccountIndexRoute
  '/login': typeof AuthLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/': typeof appIndexRoute
  '/(Auth)/create-account/': typeof AuthCreateAccountIndexRoute
  '/(Auth)/login/': typeof AuthLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-account/' | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-account' | '/login'
  id: '__root__' | '/(app)/' | '/(Auth)/create-account/' | '/(Auth)/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appIndexRoute: typeof appIndexRoute
  AuthCreateAccountIndexRoute: typeof AuthCreateAccountIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(Auth)/create-account/': {
      id: '/(Auth)/create-account/'
      path: '/create-account'
      fullPath: '/create-account/'
      preLoaderRoute: typeof AuthCreateAccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(Auth)/login/': {
      id: '/(Auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  appIndexRoute: appIndexRoute,
  AuthCreateAccountIndexRoute: AuthCreateAccountIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
